name: Waka Readme 2

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: masterking32/masterking32 # optional
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka2 # optional
          BLOCKS: ░▒▓█ # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 20 # optional
          SHOW_TIME: false # optional
          SHOW_TOTAL: false # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: false # optional
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: masterking32 # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: masterking32 # optional
          AUTHOR_EMAIL: action-bot@github.com # optional
          # you can populate email-id with secrets instead
